# Generated by Django 5.0.4 on 2024-05-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_category_color_coupon_size_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category_image',
        ),
    ]
