# Generated by Django 5.0.4 on 2024-05-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_remove_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialname', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='material_variant',
            field=models.ManyToManyField(blank=True, to='adminsite.material'),
        ),
    ]
