# Generated by Django 5.0.4 on 2024-05-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0005_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
