# Generated by Django 5.0.4 on 2024-05-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0006_delete_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
