# Generated by Django 5.0.7 on 2024-07-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminsite", "0007_delete_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
