# Generated by Django 5.0.7 on 2024-07-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminsite", "0009_product_maincategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="maincategory",
            name="images",
            field=models.ImageField(
                default="default.jph", upload_to="maincategory_images/"
            ),
        ),
    ]
