# Generated by Django 5.0.7 on 2024-07-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminsite", "0011_collection_product_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="discount",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
