# Generated by Django 5.0.7 on 2024-08-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminsite", "0012_collection_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
