# Generated by Django 5.0.7 on 2024-08-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminsite", "0013_subscriber"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscriber",
        ),
    ]
