# Generated by Django 5.0.7 on 2024-08-01 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminsite", "0014_delete_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="arrival_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="product",
            name="is_trendy",
            field=models.BooleanField(default=False),
        ),
    ]
