# Generated by Django 5.0.7 on 2024-08-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminsite", "0015_product_arrival_date_product_is_trendy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="arrival_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
