# Generated by Django 5.0.4 on 2024-05-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color_variant',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size_variant',
        ),
    ]
