# Generated by Django 5.0.4 on 2024-05-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0007_delete_cart'),
        ('cart', '0002_remove_cartitem_color_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color_variants',
            field=models.ManyToManyField(blank=True, to='adminsite.color'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size_variants',
            field=models.ManyToManyField(blank=True, to='adminsite.size'),
        ),
    ]
