# Generated by Django 5.0.7 on 2024-08-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
