# Generated by Django 5.0.7 on 2024-08-03 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart.order",
            ),
        ),
    ]
