# Generated by Django 5.0.7 on 2024-08-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_cartitem_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="order",
        ),
    ]
