# Generated by Django 5.0.7 on 2024-08-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_remove_orderitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_number",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="zip_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="size",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
