# Generated by Django 5.0.7 on 2024-08-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_remove_order_is_paid_remove_order_order_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True, default="Pending", max_length=100, null=True
            ),
        ),
    ]
